name: LLVM CLANG BUILD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DEBIAN_FRONTEND: noninteractive
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      BINUTILS_TARGET: aarch64;arm
      CLANG_TARGET: AArch64;ARM
      CLANG_VERSION: 13
      CLANG_VENDOR: "EternalX"

      GIT_USER: EternalX-project
      GIT_REPO: EternalX-project/EternalX-Clang
      GIT_BRANCH: amd64
      GIT_COMMIT_MESSAGE: "Update Clang 13 from CI build"
    
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install bc binutils-dev bison build-essential ca-certificates ccache clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev

      - name: Pushing LLVM & Binutils To Github 
        run: |
          sudo git clone "https://github.com/kdrag0n/proton-clang" proton-clang
          sudo git clone "https://$GIT_USER:$GITHUB_TOKEN@github.com/$GIT_REPO" upstream -b $GIT_BRANCH	
          cd upstream
          sudo rm -rf *
          sudo cp -r ../proton-clang/* .
          sudo git add .
          sudo git commit -am "$GIT_COMMIT_MESSAGE"
          sudo git push
